# Generated by Django 5.1 on 2024-08-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherboard', models.CharField(max_length=50)),
                ('processador', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('gpu', models.CharField(max_length=50)),
                ('fonte', models.IntegerField()),
            ],
        ),
    ]
